### PR TITLE
PNG Loading & misc fixes

### PR DESCRIPTION
**Pull request by Wolfvak**

### CODE REVIEW

**Comment by joel16** [comment]
I'd merge this but it still needs some more work.
Firstly the images that you just resized seem a little blurry. Some of them aren't the correct proportion like the backdrop.png (It should be 400 * 190)

Also these lines: https://github.com/joel16/Cyanogen3DS/pull/1/commits/614ebd691aac601279ef8669b0e67ebc9e0492b8#diff-684e680e7a915fd82c318d38e6da34a7R24

should be:
load_PNG(navbar, "romfs:/navbar.png", SF2D_PLACE_RAM);
load_PNG(backicon, "romfs:/backicon.png", SF2D_PLACE_RAM);
load_PNG(homeicon, "romfs:/homeicon.png", SF2D_PLACE_RAM);
load_PNG(multicon, "romfs:/multicon.png", SF2D_PLACE_RAM);

Apart from that everything else seems good. I'm glad you took the interest on fixing some bits, I'll be glad to merge once I have a thorough look at it. I'll probably fix the images myself.

**Comment by joel16** [comment]
One more thing, have you tried this on actual 3DS hardware to check if it works fine?

**Comment by Wolfvak** [comment]
Yeah it works. Even made a simple CIA build and it sort of works (crashes 3DS on exit tho). I knew about the scale issue and fixed it as best as I could. In any case, perhaps you could do it. I took the PNGs from your CyanogenPSP repo.

**Comment by joel16** [comment]
Hm, alright I'll have a thorough look at it. I probably might send you some pull requests to fix some tiny bits and pieces, and then you can resubmit and pull request and I'll merge it all in.

**Comment by Wolfvak** [comment]
Yeah sure

**Pull request closed without merging**
